# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import re

class Ui_Dialog(object):



    # def For LoadData in SQL
    def LoadText(self):

        # Connect Mysql
        conn = pymysql.connect(host="localhost", user="root", password="", database="Basic")

        # Connect Table Sql
        cur = conn.cursor()
        query = "select * from basic_main"
        cur.execute(query)

        # Check Data in SQL
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(cur.fetchall()):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1116, 863)
        self.tablewidget = QtWidgets.QTabWidget(Dialog)
        self.tablewidget.setGeometry(QtCore.QRect(90, 110, 951, 681))
        self.tablewidget.setObjectName("tablewidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 190, 951, 331))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(308)
        self.btnProsthese_1 = QtWidgets.QPushButton(self.tab)
        self.btnProsthese_1.setGeometry(QtCore.QRect(270, 130, 89, 25))
        self.btnProsthese_1.setObjectName("btnProsthese_1")
        self.btnDiagrafi_1 = QtWidgets.QPushButton(self.tab)
        self.btnDiagrafi_1.setGeometry(QtCore.QRect(840, 530, 101, 41))
        self.btnDiagrafi_1.setObjectName("btnDiagrafi_1")
        self.arithmosEthousas1 = QtWidgets.QLabel(self.tab)
        self.arithmosEthousas1.setGeometry(QtCore.QRect(0, 20, 131, 17))
        self.arithmosEthousas1.setObjectName("arithmosEthousas1")
        self.txtArithmosEthousas_1 = QtWidgets.QLineEdit(self.tab)
        self.txtArithmosEthousas_1.setGeometry(QtCore.QRect(140, 20, 221, 25))
        self.txtArithmosEthousas_1.setObjectName("txtArithmosEthousas_1")
        self.thesiEthousas1 = QtWidgets.QLabel(self.tab)
        self.thesiEthousas1.setGeometry(QtCore.QRect(0, 60, 121, 17))
        self.thesiEthousas1.setObjectName("thesiEthousas1")
        self.Mathimata1 = QtWidgets.QLabel(self.tab)
        self.Mathimata1.setGeometry(QtCore.QRect(0, 100, 81, 17))
        self.Mathimata1.setObjectName("Mathimata1")
        self.txtThesiEthousas_1 = QtWidgets.QLineEdit(self.tab)
        self.txtThesiEthousas_1.setGeometry(QtCore.QRect(140, 60, 221, 25))
        self.txtThesiEthousas_1.setObjectName("txtThesiEthousas_1")
        self.txtMathimata_1 = QtWidgets.QLineEdit(self.tab)
        self.txtMathimata_1.setGeometry(QtCore.QRect(140, 100, 221, 25))
        self.txtMathimata_1.setObjectName("txtMathimata_1")
        self.Search1 = QtWidgets.QLabel(self.tab)
        self.Search1.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.Search1.setLineWidth(1)
        self.Search1.setObjectName("Search1")
        self.txtSearch_Bar_1 = QtWidgets.QLineEdit(self.tab)
        self.txtSearch_Bar_1.setGeometry(QtCore.QRect(560, 14, 161, 31))
        self.txtSearch_Bar_1.setObjectName("txtSearch_Bar_1")
        self.btnLoadData_1 = QtWidgets.QPushButton(self.tab)
        self.btnLoadData_1.setGeometry(QtCore.QRect(420, 530, 121, 31))
        self.btnLoadData_1.setObjectName("btnLoadData_1")

        self.btnLoadData_1.clicked.connect(self.LoadText) #Button Load Data in SQL

        self.tablewidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 190, 951, 331))
        self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(308)
        self.ArithmosEthousas2 = QtWidgets.QLabel(self.tab_2)
        self.ArithmosEthousas2.setGeometry(QtCore.QRect(0, 20, 131, 17))
        self.ArithmosEthousas2.setObjectName("ArithmosEthousas2")
        self.Ylika1 = QtWidgets.QLabel(self.tab_2)
        self.Ylika1.setGeometry(QtCore.QRect(0, 60, 121, 17))
        self.Ylika1.setObjectName("Ylika1")
        self.Mathimata2 = QtWidgets.QLabel(self.tab_2)
        self.Mathimata2.setGeometry(QtCore.QRect(0, 100, 81, 17))
        self.Mathimata2.setObjectName("Mathimata2")
        self.txtArithmosEthousas_2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtArithmosEthousas_2.setGeometry(QtCore.QRect(140, 20, 221, 25))
        self.txtArithmosEthousas_2.setObjectName("txtArithmosEthousas_2")
        self.txtYlika_1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtYlika_1.setGeometry(QtCore.QRect(140, 60, 221, 25))
        self.txtYlika_1.setObjectName("txtYlika_1")
        self.txtMathimata_2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtMathimata_2.setGeometry(QtCore.QRect(140, 100, 221, 25))
        self.txtMathimata_2.setObjectName("txtMathimata_2")
        self.Search2 = QtWidgets.QLabel(self.tab_2)
        self.Search2.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.Search2.setLineWidth(1)
        self.Search2.setObjectName("Search2")
        self.btnDiagrafi_2 = QtWidgets.QPushButton(self.tab_2)
        self.btnDiagrafi_2.setGeometry(QtCore.QRect(840, 530, 101, 41))
        self.btnDiagrafi_2.setObjectName("btnDiagrafi_2")
        self.txtSearch_Bar_2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtSearch_Bar_2.setGeometry(QtCore.QRect(560, 14, 161, 31))
        self.txtSearch_Bar_2.setObjectName("txtSearch_Bar_2")
        self.btnProsthese_2 = QtWidgets.QPushButton(self.tab_2)
        self.btnProsthese_2.setGeometry(QtCore.QRect(270, 130, 89, 25))
        self.btnProsthese_2.setObjectName("btnProsthese_2")
        self.btnLoadData_2 = QtWidgets.QPushButton(self.tab_2)
        self.btnLoadData_2.setGeometry(QtCore.QRect(420, 530, 121, 31))
        self.btnLoadData_2.setObjectName("btnLoadData_2")
        self.tablewidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 190, 951, 331))
        self.tableWidget_4.setRowCount(10)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(231)
        self.btnDiagrafi_3 = QtWidgets.QPushButton(self.tab_3)
        self.btnDiagrafi_3.setGeometry(QtCore.QRect(840, 530, 101, 41))
        self.btnDiagrafi_3.setObjectName("btnDiagrafi_3")
        self.ArithmosEthousas3 = QtWidgets.QLabel(self.tab_3)
        self.ArithmosEthousas3.setGeometry(QtCore.QRect(0, 10, 131, 17))
        self.ArithmosEthousas3.setObjectName("ArithmosEthousas3")
        self.ThesiEthousas3 = QtWidgets.QLabel(self.tab_3)
        self.ThesiEthousas3.setGeometry(QtCore.QRect(0, 40, 131, 17))
        self.ThesiEthousas3.setObjectName("ThesiEthousas3")
        self.ThemaErevnas1 = QtWidgets.QLabel(self.tab_3)
        self.ThemaErevnas1.setGeometry(QtCore.QRect(0, 100, 131, 17))
        self.ThemaErevnas1.setObjectName("ThemaErevnas1")
        self.Mathimata3 = QtWidgets.QLabel(self.tab_3)
        self.Mathimata3.setGeometry(QtCore.QRect(0, 70, 131, 17))
        self.Mathimata3.setObjectName("Mathimata3")
        self.txtArithmosEthousas_3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtArithmosEthousas_3.setGeometry(QtCore.QRect(140, 10, 221, 25))
        self.txtArithmosEthousas_3.setObjectName("txtArithmosEthousas_3")
        self.txtThesiEthousas_3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtThesiEthousas_3.setGeometry(QtCore.QRect(140, 40, 221, 25))
        self.txtThesiEthousas_3.setObjectName("txtThesiEthousas_3")
        self.txtMathimata_3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtMathimata_3.setGeometry(QtCore.QRect(140, 70, 221, 25))
        self.txtMathimata_3.setObjectName("txtMathimata_3")
        self.txtThemaErevnas_1 = QtWidgets.QLineEdit(self.tab_3)
        self.txtThemaErevnas_1.setGeometry(QtCore.QRect(140, 100, 221, 25))
        self.txtThemaErevnas_1.setObjectName("txtThemaErevnas_1")
        self.btnProsthese_3 = QtWidgets.QPushButton(self.tab_3)
        self.btnProsthese_3.setGeometry(QtCore.QRect(270, 130, 89, 25))
        self.btnProsthese_3.setObjectName("btnProsthese_3")
        self.Serach3 = QtWidgets.QLabel(self.tab_3)
        self.Serach3.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.Serach3.setLineWidth(1)
        self.Serach3.setObjectName("Serach3")
        self.txtSearch_Bar_3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtSearch_Bar_3.setGeometry(QtCore.QRect(560, 14, 161, 31))
        self.txtSearch_Bar_3.setObjectName("txtSearch_Bar_3")
        self.btnLoadData_3 = QtWidgets.QPushButton(self.tab_3)
        self.btnLoadData_3.setGeometry(QtCore.QRect(420, 530, 121, 31))
        self.btnLoadData_3.setObjectName("btnLoadData_3")
        self.tablewidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 190, 951, 331))
        self.tableWidget_3.setRowCount(10)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(308)
        self.ArithmosGrafeiou1 = QtWidgets.QLabel(self.tab_4)
        self.ArithmosGrafeiou1.setGeometry(QtCore.QRect(0, 20, 131, 17))
        self.ArithmosGrafeiou1.setObjectName("ArithmosGrafeiou1")
        self.ThesiGrafeiou1 = QtWidgets.QLabel(self.tab_4)
        self.ThesiGrafeiou1.setGeometry(QtCore.QRect(0, 60, 131, 17))
        self.ThesiGrafeiou1.setObjectName("ThesiGrafeiou1")
        self.Kathigitis1 = QtWidgets.QLabel(self.tab_4)
        self.Kathigitis1.setGeometry(QtCore.QRect(0, 100, 131, 17))
        self.Kathigitis1.setObjectName("Kathigitis1")
        self.txtArithmosGrafeiou_1 = QtWidgets.QLineEdit(self.tab_4)
        self.txtArithmosGrafeiou_1.setGeometry(QtCore.QRect(140, 20, 221, 25))
        self.txtArithmosGrafeiou_1.setObjectName("txtArithmosGrafeiou_1")
        self.txtThesiGrafeiou_1 = QtWidgets.QLineEdit(self.tab_4)
        self.txtThesiGrafeiou_1.setGeometry(QtCore.QRect(140, 60, 221, 25))
        self.txtThesiGrafeiou_1.setObjectName("txtThesiGrafeiou_1")
        self.txtKathigitis_1 = QtWidgets.QLineEdit(self.tab_4)
        self.txtKathigitis_1.setGeometry(QtCore.QRect(140, 100, 221, 25))
        self.txtKathigitis_1.setObjectName("txtKathigitis_1")
        self.btnProsthese_4 = QtWidgets.QPushButton(self.tab_4)
        self.btnProsthese_4.setGeometry(QtCore.QRect(270, 130, 89, 25))
        self.btnProsthese_4.setObjectName("btnProsthese_4")
        self.btnDiagrafi_4 = QtWidgets.QPushButton(self.tab_4)
        self.btnDiagrafi_4.setGeometry(QtCore.QRect(840, 530, 101, 41))
        self.btnDiagrafi_4.setObjectName("btnDiagrafi_4")
        self.Search4 = QtWidgets.QLabel(self.tab_4)
        self.Search4.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.Search4.setLineWidth(1)
        self.Search4.setObjectName("Search4")
        self.txtSearch_Bar_4 = QtWidgets.QLineEdit(self.tab_4)
        self.txtSearch_Bar_4.setGeometry(QtCore.QRect(560, 14, 161, 31))
        self.txtSearch_Bar_4.setObjectName("txtSearch_Bar_4")
        self.btnLoadData_4 = QtWidgets.QPushButton(self.tab_4)
        self.btnLoadData_4.setGeometry(QtCore.QRect(420, 530, 121, 31))
        self.btnLoadData_4.setObjectName("btnLoadData_4")
        self.tablewidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 170, 621, 341))
        self.tableWidget_5.setRowCount(10)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(298)
        self.txtArithmosDiadromou_1 = QtWidgets.QLineEdit(self.tab_5)
        self.txtArithmosDiadromou_1.setGeometry(QtCore.QRect(150, 20, 221, 25))
        self.txtArithmosDiadromou_1.setObjectName("txtArithmosDiadromou_1")
        self.txtThesiDiadromou_1 = QtWidgets.QLineEdit(self.tab_5)
        self.txtThesiDiadromou_1.setGeometry(QtCore.QRect(150, 70, 221, 25))
        self.txtThesiDiadromou_1.setObjectName("txtThesiDiadromou_1")
        self.ArithmosDiadromou1 = QtWidgets.QLabel(self.tab_5)
        self.ArithmosDiadromou1.setGeometry(QtCore.QRect(0, 20, 151, 17))
        self.ArithmosDiadromou1.setObjectName("ArithmosDiadromou1")
        self.ThesiDiadromou1 = QtWidgets.QLabel(self.tab_5)
        self.ThesiDiadromou1.setGeometry(QtCore.QRect(0, 70, 131, 17))
        self.ThesiDiadromou1.setObjectName("ThesiDiadromou1")
        self.Search5 = QtWidgets.QLabel(self.tab_5)
        self.Search5.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.Search5.setLineWidth(1)
        self.Search5.setObjectName("Search5")
        self.txtSearch_Bar_5 = QtWidgets.QLineEdit(self.tab_5)
        self.txtSearch_Bar_5.setGeometry(QtCore.QRect(560, 14, 161, 31))
        self.txtSearch_Bar_5.setObjectName("txtSearch_Bar_5")
        self.btnProsthese_5 = QtWidgets.QPushButton(self.tab_5)
        self.btnProsthese_5.setGeometry(QtCore.QRect(280, 100, 89, 25))
        self.btnProsthese_5.setObjectName("btnProsthese_5")
        self.btnDiagrafi_5 = QtWidgets.QPushButton(self.tab_5)
        self.btnDiagrafi_5.setGeometry(QtCore.QRect(520, 520, 101, 41))
        self.btnDiagrafi_5.setObjectName("btnDiagrafi_5")
        self.btnLoadData_5 = QtWidgets.QPushButton(self.tab_5)
        self.btnLoadData_5.setGeometry(QtCore.QRect(260, 530, 121, 31))
        self.btnLoadData_5.setObjectName("btnLoadData_5")
        self.tablewidget.addTab(self.tab_5, "")

        self.retranslateUi(Dialog)
        self.tablewidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Αριθμός Αίθουσας"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Θέση Αίθουσας"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Μαθήματα"))
        self.btnProsthese_1.setText(_translate("Dialog", "Πρόσθεσε"))
        self.btnDiagrafi_1.setText(_translate("Dialog", "Διαγραφη"))
        self.arithmosEthousas1.setText(_translate("Dialog", "Αριθμός Αίθουσας :"))
        self.thesiEthousas1.setText(_translate("Dialog", "Θέση Αίθουσας :"))
        self.Mathimata1.setText(_translate("Dialog", "Μαθήματα :"))
        self.Search1.setText(_translate("Dialog", "Search :"))
        self.btnLoadData_1.setText(_translate("Dialog", "Load Data"))
        self.tablewidget.setTabText(self.tablewidget.indexOf(self.tab), _translate("Dialog", "Αίθουσα Διδασκαλίας"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Αριθμός Αίθουσας"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Υλικά"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Μαθήματα"))
        self.ArithmosEthousas2.setText(_translate("Dialog", "Αριθμός Αίθουσας :"))
        self.Ylika1.setText(_translate("Dialog", "Υλικά :"))
        self.Mathimata2.setText(_translate("Dialog", "Μαθήματα :"))
        self.Search2.setText(_translate("Dialog", "Search :"))
        self.btnDiagrafi_2.setText(_translate("Dialog", "Διαγραφη"))
        self.btnProsthese_2.setText(_translate("Dialog", "Πρόσθεσε"))
        self.btnLoadData_2.setText(_translate("Dialog", "Load Data"))
        self.tablewidget.setTabText(self.tablewidget.indexOf(self.tab_2), _translate("Dialog", "Εργαστήριο Εκπαίδευσης"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Αριθμός Αίθουσας"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Θέση Αίθουσας"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Μαθήματα"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Θέμα Έρευνας"))
        self.btnDiagrafi_3.setText(_translate("Dialog", "Διαγραφη"))
        self.ArithmosEthousas3.setText(_translate("Dialog", "Αριθμός Αίθουσας :"))
        self.ThesiEthousas3.setText(_translate("Dialog", "Θέση Αίθουσας :"))
        self.ThemaErevnas1.setText(_translate("Dialog", "Θέμα Ερεύνας :"))
        self.Mathimata3.setText(_translate("Dialog", "Μάθημα :"))
        self.btnProsthese_3.setText(_translate("Dialog", "Πρόσθεσε"))
        self.Serach3.setText(_translate("Dialog", "Search :"))
        self.btnLoadData_3.setText(_translate("Dialog", "Load Data"))
        self.tablewidget.setTabText(self.tablewidget.indexOf(self.tab_3), _translate("Dialog", "Ερευνιτικό Εργαστήριο"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Αριθμός Γραφείου"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Θέση Γραφείου"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Καθηγητές"))
        self.ArithmosGrafeiou1.setText(_translate("Dialog", "Αριθμός Γραφείου :"))
        self.ThesiGrafeiou1.setText(_translate("Dialog", "Θέση Γραφείου :"))
        self.Kathigitis1.setText(_translate("Dialog", "Καθηγητής :"))
        self.btnProsthese_4.setText(_translate("Dialog", "Πρόσθεσε"))
        self.btnDiagrafi_4.setText(_translate("Dialog", "Διαγραφη"))
        self.Search4.setText(_translate("Dialog", "Search :"))
        self.btnLoadData_4.setText(_translate("Dialog", "Load Data"))
        self.tablewidget.setTabText(self.tablewidget.indexOf(self.tab_4), _translate("Dialog", "Γραφεία"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Αριθμός Διαδρόμου"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Θέση Διαδρόμου"))
        self.ArithmosDiadromou1.setText(_translate("Dialog", "Αριθμός Διαδρόμου :"))
        self.ThesiDiadromou1.setText(_translate("Dialog", "Θέση Διαδρόμου :"))
        self.Search5.setText(_translate("Dialog", "Search :"))
        self.btnProsthese_5.setText(_translate("Dialog", "Πρόσθεσε"))
        self.btnDiagrafi_5.setText(_translate("Dialog", "Διαγραφη"))
        self.btnLoadData_5.setText(_translate("Dialog", "Load Data"))
        self.tablewidget.setTabText(self.tablewidget.indexOf(self.tab_5), _translate("Dialog", "Διάδρομοι"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
