
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import create_database as db
import os



class Ui_Epoptis(object):

    def MessageBox(self, title, message):
        mess = QtWidgets.QMessageBox()

        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

     































    def setupUi(self, Epoptis):
        Epoptis.setObjectName("Epoptis")
        Epoptis.resize(797, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Epoptis.sizePolicy().hasHeightForWidth())
        Epoptis.setSizePolicy(sizePolicy)
        Epoptis.setMinimumSize(QtCore.QSize(797, 647))
        Epoptis.setMaximumSize(QtCore.QSize(797, 647))
        Epoptis.setBaseSize(QtCore.QSize(797, 647))
        font = QtGui.QFont()
        font.setPointSize(10)
        Epoptis.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("media/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Epoptis.setWindowIcon(icon)
        Epoptis.setIconSize(QtCore.QSize(24, 24))
        Epoptis.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Epoptis)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.equipment = QtWidgets.QWidget()
        self.equipment.setObjectName("equipment")
        self.equipment_table = QtWidgets.QTableWidget(self.equipment)
        self.equipment_table.setEnabled(True)
        self.equipment_table.setGeometry(QtCore.QRect(0, 210, 795, 301))
        self.equipment_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.equipment_table.setFont(font)
        self.equipment_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.equipment_table.setTabletTracking(False)
        self.equipment_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.equipment_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.equipment_table.setAutoFillBackground(False)
        self.equipment_table.setFrameShape(QtWidgets.QFrame.Box)
        self.equipment_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.equipment_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.equipment_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.equipment_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.equipment_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.equipment_table.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.equipment_table.setAlternatingRowColors(False)
        self.equipment_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.equipment_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.equipment_table.setShowGrid(True)
        self.equipment_table.setGridStyle(QtCore.Qt.DashLine)
        self.equipment_table.setWordWrap(False)
        self.equipment_table.setRowCount(10)
        self.equipment_table.setColumnCount(18)
        self.equipment_table.setObjectName("equipment_table")
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.equipment_table.setItem(0, 0, item)
        self.equipment_table.horizontalHeader().setCascadingSectionResizes(False)
        self.equipment_table.horizontalHeader().setMinimumSectionSize(39)
        self.equipment_table.verticalHeader().setStretchLastSection(False)
        self.search_label = QtWidgets.QLabel(self.equipment)
        self.search_label.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.search_label.setFont(font)
        self.search_label.setObjectName("search_label")
        self.equip_search_info_label = QtWidgets.QLabel(self.equipment)
        self.equip_search_info_label.setGeometry(QtCore.QRect(0, 190, 381, 16))
        self.equip_search_info_label.setObjectName("equip_search_info_label")
        self.line = QtWidgets.QFrame(self.equipment)
        self.line.setGeometry(QtCore.QRect(460, 0, 21, 211))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.equipment)
        self.line_2.setGeometry(QtCore.QRect(0, 20, 181, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_search_xwrou = QtWidgets.QLabel(self.equipment)
        self.label_search_xwrou.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setBold(False)
        font.setWeight(50)
        self.label_search_xwrou.setFont(font)
        self.label_search_xwrou.setObjectName("label_search_xwrou")
        self.label_search_yliko = QtWidgets.QLabel(self.equipment)
        self.label_search_yliko.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_search_yliko.setObjectName("label_search_yliko")
        self.label_search_daneismos = QtWidgets.QLabel(self.equipment)
        self.label_search_daneismos.setGeometry(QtCore.QRect(10, 100, 141, 16))
        self.label_search_daneismos.setObjectName("label_search_daneismos")
        self.label_search_keywords = QtWidgets.QLabel(self.equipment)
        self.label_search_keywords.setGeometry(QtCore.QRect(10, 130, 201, 16))
        self.label_search_keywords.setObjectName("label_search_keywords")
        self.label_search_katigoria_ylikou = QtWidgets.QLabel(self.equipment)
        self.label_search_katigoria_ylikou.setGeometry(QtCore.QRect(10, 160, 171, 16))
        self.label_search_katigoria_ylikou.setObjectName("label_search_katigoria_ylikou")
        self.search_xwrou_input = QtWidgets.QLineEdit(self.equipment)
        self.search_xwrou_input.setGeometry(QtCore.QRect(230, 40, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.search_xwrou_input.setFont(font)
        self.search_xwrou_input.setText("")
        self.search_xwrou_input.setObjectName("search_xwrou_input")
        self.search_ylikou_input = QtWidgets.QLineEdit(self.equipment)
        self.search_ylikou_input.setGeometry(QtCore.QRect(230, 70, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.search_ylikou_input.setFont(font)
        self.search_ylikou_input.setText("")
        self.search_ylikou_input.setObjectName("search_ylikou_input")
        self.search_daneismou_input = QtWidgets.QLineEdit(self.equipment)
        self.search_daneismou_input.setGeometry(QtCore.QRect(230, 100, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.search_daneismou_input.setFont(font)
        self.search_daneismou_input.setObjectName("search_daneismou_input")
        self.search_keywords_input = QtWidgets.QLineEdit(self.equipment)
        self.search_keywords_input.setGeometry(QtCore.QRect(230, 130, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.search_keywords_input.setFont(font)
        self.search_keywords_input.setText("")
        self.search_keywords_input.setObjectName("search_keywords_input")
        self.search_katigoria_input = QtWidgets.QLineEdit(self.equipment)
        self.search_katigoria_input.setGeometry(QtCore.QRect(230, 160, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.search_katigoria_input.setFont(font)
        self.search_katigoria_input.setObjectName("search_katigoria_input")
        self.equipment_search_button = QtWidgets.QPushButton(self.equipment)
        self.equipment_search_button.setGeometry(QtCore.QRect(350, 100, 121, 23))
        self.equipment_search_button.setObjectName("equipment_search_button")
        self.equipment_management_label = QtWidgets.QLabel(self.equipment)
        self.equipment_management_label.setGeometry(QtCore.QRect(480, 10, 131, 16))
        self.equipment_management_label.setObjectName("equipment_management_label")
        self.line_3 = QtWidgets.QFrame(self.equipment)
        self.line_3.setGeometry(QtCore.QRect(470, 20, 181, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.equipment_management_info_label = QtWidgets.QLabel(self.equipment)
        self.equipment_management_info_label.setGeometry(QtCore.QRect(480, 190, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.equipment_management_info_label.setFont(font)
        self.equipment_management_info_label.setObjectName("equipment_management_info_label")
        self.delete_button_ylikou = QtWidgets.QPushButton(self.equipment)
        self.delete_button_ylikou.setGeometry(QtCore.QRect(480, 110, 111, 23))
        self.delete_button_ylikou.setObjectName("delete_button_ylikou")
        self.id_ylikou_management_label = QtWidgets.QLabel(self.equipment)
        self.id_ylikou_management_label.setGeometry(QtCore.QRect(480, 70, 91, 16))
        self.id_ylikou_management_label.setObjectName("id_ylikou_management_label")
        self.id_ylikou_management_input = QtWidgets.QLineEdit(self.equipment)
        self.id_ylikou_management_input.setGeometry(QtCore.QRect(570, 70, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.id_ylikou_management_input.setFont(font)
        self.id_ylikou_management_input.setObjectName("id_ylikou_management_input")
        self.edit_button_ylikou = QtWidgets.QPushButton(self.equipment)
        self.edit_button_ylikou.setGeometry(QtCore.QRect(620, 110, 131, 23))
        self.edit_button_ylikou.setObjectName("edit_button_ylikou")
        self.tabWidget.addTab(self.equipment, "")
        self.logged_in_as_label = QtWidgets.QLabel(self.centralwidget)
        self.logged_in_as_label.setGeometry(QtCore.QRect(480, 550, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.logged_in_as_label.setFont(font)
        self.logged_in_as_label.setObjectName("logged_in_as_label")
        self.User_name_Label = QtWidgets.QLabel(self.centralwidget)
        self.User_name_Label.setGeometry(QtCore.QRect(600, 550, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.User_name_Label.setFont(font)
        self.User_name_Label.setText("")
        self.User_name_Label.setScaledContents(False)
        self.User_name_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.User_name_Label.setWordWrap(False)
        self.User_name_Label.setObjectName("User_name_Label")
        self.access_areas_label = QtWidgets.QLabel(self.centralwidget)
        self.access_areas_label.setGeometry(QtCore.QRect(10, 550, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setBold(True)
        font.setWeight(75)
        self.access_areas_label.setFont(font)
        self.access_areas_label.setObjectName("access_areas_label")
        self.access_areas_names_label = QtWidgets.QLabel(self.centralwidget)
        self.access_areas_names_label.setGeometry(QtCore.QRect(160, 550, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        self.access_areas_names_label.setFont(font)
        self.access_areas_names_label.setLineWidth(1)
        self.access_areas_names_label.setText("")
        self.access_areas_names_label.setTextFormat(QtCore.Qt.PlainText)
        self.access_areas_names_label.setScaledContents(True)
        self.access_areas_names_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.access_areas_names_label.setWordWrap(False)
        self.access_areas_names_label.setIndent(-1)
        self.access_areas_names_label.setObjectName("access_areas_names_label")
        Epoptis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Epoptis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        Epoptis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Epoptis)
        self.statusbar.setObjectName("statusbar")
        Epoptis.setStatusBar(self.statusbar)

        self.retranslateUi(Epoptis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Epoptis)

    def retranslateUi(self, Epoptis):
        _translate = QtCore.QCoreApplication.translate
        Epoptis.setWindowTitle(_translate("Epoptis", "Admin Access "))
        self.equipment_table.setSortingEnabled(False)
        item = self.equipment_table.horizontalHeaderItem(0)
        item.setText(_translate("Epoptis", "ID Υλικού"))
        item = self.equipment_table.horizontalHeaderItem(1)
        item.setText(_translate("Epoptis", "Χώρος Υλικού"))
        item = self.equipment_table.horizontalHeaderItem(2)
        item.setText(_translate("Epoptis", "Χαρακτηριστικά/Χρήση Υλικού"))
        item = self.equipment_table.horizontalHeaderItem(3)
        item.setText(_translate("Epoptis", "Τύπος Υλικού"))
        item = self.equipment_table.horizontalHeaderItem(4)
        item.setText(_translate("Epoptis", "Ποσότητα"))
        item = self.equipment_table.horizontalHeaderItem(5)
        item.setText(_translate("Epoptis", "Κατάσταση Υλικού"))
        item = self.equipment_table.horizontalHeaderItem(6)
        item.setText(_translate("Epoptis", "Εταιρία "))
        item = self.equipment_table.horizontalHeaderItem(7)
        item.setText(_translate("Epoptis", "Μοντέλο"))
        item = self.equipment_table.horizontalHeaderItem(8)
        item.setText(_translate("Epoptis", "Ακριβής Ονομασία"))
        item = self.equipment_table.horizontalHeaderItem(9)
        item.setText(_translate("Epoptis", "Χρόνος Κτήσης"))
        item = self.equipment_table.horizontalHeaderItem(10)
        item.setText(_translate("Epoptis", "Σειριακός Αριθμός"))
        item = self.equipment_table.horizontalHeaderItem(11)
        item.setText(_translate("Epoptis", "Σκοπός Χρήσης"))
        item = self.equipment_table.horizontalHeaderItem(12)
        item.setText(_translate("Epoptis", "Βάρος"))
        item = self.equipment_table.horizontalHeaderItem(13)
        item.setText(_translate("Epoptis", "Διαθεσιμότητα"))
        item = self.equipment_table.horizontalHeaderItem(14)
        item.setText(_translate("Epoptis", "Δ.Μετακίνησης"))
        item = self.equipment_table.horizontalHeaderItem(15)
        item.setText(_translate("Epoptis", "Κατάσταση Δανεισμού"))
        item = self.equipment_table.horizontalHeaderItem(16)
        item.setText(_translate("Epoptis", "Κατηγορία"))
        item = self.equipment_table.horizontalHeaderItem(17)
        item.setText(_translate("Epoptis", "Υποκατηγορίες"))
        __sortingEnabled = self.equipment_table.isSortingEnabled()
        self.equipment_table.setSortingEnabled(False)
        self.equipment_table.setSortingEnabled(__sortingEnabled)
        self.search_label.setText(_translate("Epoptis", "Αναζήτηση Υλικών"))
        self.equip_search_info_label.setText(_translate("Epoptis", "Για αναζήτηση εισάγετε κάποια πληροφορία στα παραπάνω πλαίσια."))
        self.label_search_xwrou.setText(_translate("Epoptis", "Χώρος :"))
        self.label_search_yliko.setText(_translate("Epoptis", "Τύπος Υλικού :"))
        self.label_search_daneismos.setText(_translate("Epoptis", "Κατάσταση Δανεισμού :"))
        self.label_search_keywords.setText(_translate("Epoptis", "Λέξεις Κλειδιά(χωρίστε με κόμμα) :"))
        self.label_search_katigoria_ylikou.setText(_translate("Epoptis", "Κατηγορία Υλικού :"))
        self.equipment_search_button.setText(_translate("Epoptis", "Αναζήτηση Υλικού"))
        self.equipment_management_label.setText(_translate("Epoptis", "Διαχείριση Υλικών"))
        self.equipment_management_info_label.setText(_translate("Epoptis", "Εισάγετε ID υλικού για διαγραφή ή επεξεργασία."))
        self.delete_button_ylikou.setText(_translate("Epoptis", "Διαγραφή Υλικού"))
        self.id_ylikou_management_label.setText(_translate("Epoptis", "ID Υλικού :"))
        self.edit_button_ylikou.setText(_translate("Epoptis", "Επεξεργασία Υλικού"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.equipment), _translate("Epoptis", "Διαχείριση Υλικού Χώρων"))
        self.logged_in_as_label.setText(_translate("Epoptis", "Logged in as:"))
        self.access_areas_label.setText(_translate("Epoptis", "Χώροι Πρόσβασης :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Epoptis = QtWidgets.QMainWindow()
    ui = Ui_Epoptis()
    ui.setupUi(Epoptis)
    Epoptis.show()
    sys.exit(app.exec_())

